In [26]:
import random
import numpy as np


In [51]:
A = [[] for i in range(10)]
A

[[], [], [], [], [], [], [], [], [], []]

In [32]:
'%0.2f'%0.7777777

'0.78'

In [33]:
B = copy(A)

NameError: name 'copy' is not defined

In [55]:
B = [1,2,3,4,5]
B.sort(key=lambda x)

array([1, 2, 3, 4, 5])

In [45]:
print(B)

[]


In [10]:
random.uniform(0.1,3.5)

1.9422265473514313

In [13]:
random.randint(1,9)

7

In [2]:
dict = {
    "sorvete": "chocolate",
    "lanche": "bolacha",
    "fruta": "mamão"
}

In [4]:
print(dict.get("fruta"))

mamão


In [5]:
dict.clear()
dict

{}

In [4]:
lista = [1, 2, 3, 4, 5, 7, 8, 9, 10]

In [5]:
lista[lista%2 == 0]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [3]:
import numpy as np

In [7]:
a = np.array(lista)

In [11]:
b = a[a%2 == 0]
b

array([ 2,  4,  8, 10])

In [10]:
sum(b)

24

In [12]:
b*2

array([ 4,  8, 16, 20])

In [1]:
juizes = ["a", "b", "c", "d"]

In [3]:
juizes[1][1].size


IndexError: string index out of range

In [4]:
import numpy as np

In [9]:
a = np.zeros(16).reshape(4,4)

In [10]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1]:
L= [1,2,3]

In [15]:
L[3].extend([11,23,33])

In [16]:
L

[1,
 2,
 3,
 [11, 22, 33, 7, 8, 9, 11, 23, 33],
 11,
 22,
 33,
 11,
 22,
 33,
 11,
 23,
 33]

In [5]:
L.insert([111,222,333])

TypeError: insert() takes exactly 2 arguments (1 given)

In [17]:
sum(L[3])

157

In [18]:
a =[1,2,3]

In [19]:
b =[a,a]

In [20]:
b

[[1, 2, 3], [1, 2, 3]]